### ISSUE TITLE
Unable to publish to forge because of vendor/

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-proxysql#10]
Hi,

somehow vendor/ is included in the created pkg. Then the upload to the forge fails because of the size. I'm not able to reproduce this locally. Some basic fiddling is available in https://github.com/voxpupuli/puppet-proxysql/pull/8

**Comment by alexjfisher** [comment]
> [If you have both a .pmtignore and a .gitignore file, the Puppet module tool will read the .pmtignore file over the .gitignore.](https://docs.puppet.com/puppet/4.8/modules_publishing.html#set-files-to-be-ignored)

My guess is this [commit](https://github.com/voxpupuli/modulesync_config/commit/4f51770f4a93f7fd2209cf19d01cd123770e5af3) broke things.

**Comment by mcrauwel** [comment]
If I understand that link correctly, adding the files from `.gitignore` also to `.pmtignore` and then doing the modulesync again should fix this?
