### ISSUE TITLE
Update dependency from camptocamp-systemd to puppet-systemd

### ISSUE THREAD

**Issue by sazzle2611** [voxpupuli/puppet-proxysql#182]

**Comment by smortex** [comment]
Was done in #177 but not released yet

**Comment by sazzle2611** [comment]
I just realised as I learnt how to create PR's tonight so I went to do one and found the module already updated.

One thing I don't understand though is the name is puppet/systemd but shouldn't it be puppet-systemd or doesn't it matter? Only asking so I know for the future.

Thanks,
Sarah

**Comment by kenyon** [comment]
> @smortex I just realised as I learnt how to create PR's tonight so I went to do one and found the module already updated.
> 
> One thing I don't understand though is the name is puppet/systemd but shouldn't it be puppet-systemd or doesn't it matter? Only asking so I know for the future.
> 
> Thanks, Sarah

They are equivalent. See https://github.com/voxpupuli/metadata-json-lint/blob/6919241c0fa0ad791b939fb23595ca7e5aee500b/lib/metadata-json-lint/schema.rb#L28 for example where the regexp allows either `/` or `-`.

**Comment by sazzle2611** [comment]
Thanks @kenyon
