### ISSUE TITLE
Deprecation request.

### ISSUE THREAD

**Issue by TheMeier** [voxpupuli/puppet-proxysql#213]
This module looks abandoned, we should consider deprecating it.

**Comment by alexjfisher** [comment]
I've not worked on it for a bit as I changed companies.  I don't think it was in that bad a shape though, and I don't know of any better replacement.  ProxySQL itself is still actively developed, so I'm not keen on deprecated this.  I think it'd make it much harder for anyone using the module to contribute.  https://github.com/voxpupuli/puppet-proxysql/pull/191 wasn't _that_ long ago either.

As for the current test failures, has anyone got an idea about Oracle Linux failing?  I vaguely recall seeing similar failures in a different module.  Can't remember where though...

**Comment by TheMeier** [comment]
Last release was 2021 though

**Comment by alexjfisher** [comment]
yeah, so if we can fix the tests, modulesync and get a release out, that'd be great.  There was even an offer of help in https://github.com/voxpupuli/puppet-proxysql/issues/195 and several thumbs up from other people who would like to see it too.

> Apr 30 22:06:48 oracle7-64-puppet7.example.com systemd[1]: New main PID 1188 does not belong to service, and PID file is not owned by root. Refusing.

Is the error.  Since we've not had a release in years, I'd also hold back on removing any EOL OSes until after a release has been made.

**Comment by saz** [comment]
I'm actively using this module and I'm happy to spend some time on it, but can't tell, when this will be possible. :(

**Comment by saz** [comment]
> As for the current test failures, has anyone got an idea about Oracle Linux failing? I vaguely recall seeing similar failures in a different module. Can't remember where though...

```
diff --git a/manifests/service.pp b/manifests/service.pp
index 81c870c..89ced66 100644
--- a/manifests/service.pp
+++ b/manifests/service.pp
@@ -19,8 +19,10 @@ class proxysql::service {
       notify   => Service[$proxysql::service_name],
     }
     service { $proxysql::service_name:
-      ensure => $proxysql::service_ensure,
-      enable => true,
+      ensure     => $proxysql::service_ensure,
+      enable     => true,
+      hasrestart => true,
+      hasstatus  => true,
     }
   } else {
     if $proxysql::restart {
```
will fix some errors, but there are more. I'll try to work on it this or next week to get the `modulesync` MR in a mergeable state.

Besides that, I guess it makes sense to stop supporting old versions of proxysql. Currently, 2.2 to 2.7 are maintained.

**Comment by saz** [comment]
Well...
```
      Puppet::PreformattedError:
        Evaluation Error: Error while evaluating a Resource Statement, Apt::Source[proxysql_repo]: parameter 'repos' expects a String[1] value, got String (file: /home/saz/src/puppet/puppet-proxysql/spec/fixtures/modules/proxysql/manifests/repo.pp, line: 19) on node stewie.home.saz.sh
 ```
 
 Any good way to solve this? Setting it to `' '` is working, but looks... ugly :)

**Comment by saz** [comment]
@TheMeier As people (like me) are still relying on this module and I'm trying to get it as good as possible, I think we can close this request?
