### ISSUE TITLE
Mysql query rule changed

### ISSUE THREAD

**Issue by powercycleagain** [voxpupuli/puppet-proxysql#24]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.1
- Ruby: 2.0.0p648
- Distribution: Centos7
- Module version: 1.1.2

## How to reproduce (e.g Puppet code you use)
We use the galaera check script (https://github.com/Tusamarco/proxy_sql_tools/blob/master/galera_check.pl) in combination with proxysql and query_rules. Puppet runs now give a "notice" but don't change data. There are no changes without the "FOR" keyword in the query "SELECT. * FOR UPDATE".

Hiera data:
        'mysql_query_rule-1':
            'rule_id': '1'
            'active': '1'
            'destination_hostgroup': '1'
            'match_pattern': '^SELECT .*'
            'apply': '0'
        'mysql_query_rule-2':
            'rule_id': '2'
            'active': '1'
            'destination_hostgroup': '2'
            'match_pattern': '^SELECT .* FOR UPDATE'
            'apply': '1'

## What are you seeing
Info: Applying configuration version '1490088162'
Notice: /Stage[main]/Dbproxy::Queryrule/Proxy_mysql_query_rule[mysql_query_rule-2]/match_pattern: match_pattern changed '^SELECT' to '^SELECT .* FOR UPDATE'
Notice: /Stage[main]/Dbproxy::Queryrule/Proxy_mysql_query_rule[mysql_query_rule-2]/negate_match_pattern: negate_match_pattern changed '.*' to '0'
Notice: Applied catalog in 7.99 seconds

Before and after puppet run (select * from mysql_servers):
| rule_id | match_pattern         |
| 1       | ^SELECT.*             |
| 2       | ^SELECT .* FOR UPDATE |

**Comment by mcrauwel** [comment]
thanks for your report, I'll investigate asap.

**Comment by narcisbcn** [comment]
Same issue here
`Info: Applying configuration version '1496247689'
Notice: /Stage[main]/Profile_proxysql::Rating/Proxy_mysql_query_rule[select_for_update]/match_pattern: match_pattern changed '^SELECT' to '^SELECT .* FOR UPDATE$'
Notice: /Stage[main]/Profile_proxysql::Rating/Proxy_mysql_query_rule[select_for_update]/negate_match_pattern: negate_match_pattern changed '.*' to '0'`

**Comment by mcrauwel** [comment]
sorry for taking so long on this... I finally got around updating our test-infra to use this feature and searching and fixing the bug...
