### ISSUE TITLE
Module push 'OFFLINE_SOFT' back online

### ISSUE THREAD

**Issue by powercycleagain** [voxpupuli/puppet-proxysql#25]
## Affected Puppet, Ruby, OS and module versions/distributions
Puppet: 4.8.1
Ruby: 2.0.0p648
Distribution: Centos7
Module version: 1.1.2

## How to reproduce (e.g Puppet code you use)
We use the galaera check script (https://github.com/Tusamarco/proxy_sql_tools/blob/master/galera_check.pl) in combination with proxysql. After each run puppet push the "OFFLINE_SOFT" servers back online.

## What are you seeing
/Stage[main]/Dbproxy::Mysqlserver/Proxy_mysql_server[*.*.*.64:3306-1]/status defined 'status' as 'ONLINE'

select hostgroup_id, status from mysql_servers;
+--------------+-------------+--------------+
| hostgroup_id | hostname    | status       |
+--------------+-------------+--------------+
| 1            | *.*.*.63 | ONLINE       |
| 1            | *.*.*.64 | ONLINE       |
| 1            | *.*.*.65 | ONLINE       |
| 1            | *.*.*.66 | ONLINE       |
| 2            | *.*.*.63 | ONLINE       |
| 2            | *.*.*.64 | OFFLINE_SOFT |
| 2            | *.*.*.65 | OFFLINE_SOFT |
| 2            | *.*.*.66 | OFFLINE_SOFT |
+--------------+-------------+--------------+

## What behaviour did you expect instead
Keep the status "OFFLINE_SOFT".

**Comment by mcrauwel** [comment]
how did you define you `proxy_mysql_server` resources?

maybe I can drop the default values for the fields in puppet and leave those as 'unmanaged'. This is  due to the nature of puppet which wants to restore all reasources it manages to the state it has them in the config. If you don't specify a 'status' currently it will use 'ONLINE' as default...

**Comment by powercycleagain** [comment]
This is configured in hiera without the status field:
mysqlservers:
        '*.*.*.63:3306-1':
            'hostname': '*.*.*.63'
            'port': '3306'
            'hostgroup_id': '1'
            'max_connections': '200'

Quick fix for us:
lib/puppet/type/proxy_mysql_server.rb
 52 #  newproperty(:status) do
 53 #    desc 'Server status.'
 54 #    defaultto :ONLINE
 55 #    newvalues(:ONLINE, :SHUNNED, :OFFLINE_SOFT, :OFFLINE_HARD)
 56 #  end

**Comment by mcrauwel** [comment]
I'll check which fields have a database default and remove default values for those in the type/provider.
