### ISSUE TITLE
New versions of proxysql

### ISSUE THREAD

**Issue by narcisbcn** [voxpupuli/puppet-proxysql#38]
## How to evolve this project

Hi,
I would like to get some feedback or just open a discussion about how we can progress with new proxysql versions, those will introduce new fields in tables, then some compatibility could be broken.

Also, another issue candidate I see: we use automatic failover techniques, then to make this module compatible to our design is to specify to the provider do not look at some specific fields such as hostgroups or status, otherwise if the failover happens, puppet would move back the promoted slave to the original hostgroup (readers) set by puppet.

I have work done regarding this second step.

Thoughts?

Cheers

**Comment by mcrauwel** [comment]
As for new fields and features: it's on my radar, just haven't had time to look into it...

For the failover techniques: you could set the puppet command to not load the config to runtime so puppet does not touch the active runtime tables. We ended up not managing `STATUS` but we do manage `hostgroup_id`.

If you have work done, always welcome to PR.
