### ISSUE TITLE
readd stdlib dependency; bump mysql/apt dependency

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-proxysql#65]
in https://github.com/voxpupuli/puppet-proxysql/pull/64 we had to remove stdlib, which is a direct dependency.  All this because of the current mysql release pulling in legacy stdlib... We need to update/readd dependencies after https://tickets.puppetlabs.com/browse/MODULES-7747 is solved.

**Comment by mcrauwel** [comment]
@bastelfreak this looks fixed right?

**Comment by bastelfreak** [comment]
right, I will readd stdlib
