### ISSUE TITLE
puppet 5 compatibility (bump dependencies for puppetlabs-apt to something more modern)

### ISSUE THREAD

**Issue by jackdpeterson** [voxpupuli/puppet-proxysql#66]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby: 2.5.1.p57
- Distribution: Ubuntu 18.04
- Module version: 1.1.2 (I see master has an updated dependency for puppetlabs-apt in metadata.json) ... does this just need a new release?

## How to reproduce (e.g Puppet code you use)
This isn't specifically a problem with this module per-se ... rather, this module just sets a maximum version for puppetlabs-apt that's much lower than most other modern puppet modules out there resulting in librarian-puppet unresolvable dependency trees.

```
[Librarian]   Module puppet-proxysql found versions: 1.1.2, 1.1.1, 1.1.0
[Librarian]     Checking puppet-proxysql/1.1.2 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved puppet-proxysql (= 1.1.2) <https://forgeapi.puppetlabs.com> at puppet-proxysql/1.1.2 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved puppet-proxysql (= 1.1.2) <https://forgeapi.puppetlabs.com>
[Librarian] Conflict between puppetlabs-apt (< 5.0.0, >= 4.4.0) <https://forgeapi.puppetlabs.com> and puppetlabs-apt (< 3.0.0, >= 2.1.0) <https://forgeapi.puppetlabs.com>

```

As my sample output here when doing 
```bash
librarian-puppet install -v
```

**Comment by bastelfreak** [comment]
please have a look at https://github.com/voxpupuli/puppet-proxysql/issues/65

**Comment by jackdpeterson** [comment]
Okay, thanks :-)
