### ISSUE TITLE
Installation failure on deb 9.5

### ISSUE THREAD

**Issue by CyberLine** [voxpupuli/puppet-proxysql#69]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2
- Ruby: 2.3.3p222
- Distribution: Debian 9.5
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)

When using `::proxysql` class from this class, under my environment, the installation fails due to missing run of `apt-get update` after adding the repository and key.

## What are you seeing

after first apply of using proxysql class, i have to manually do a `apt-get update` and then run `puppet agent -t` to get those manifests working.

## Output log

`Notice: /Stage[main]/Proxysql::Repo/Apt::Source[proxysql_repo]/Apt::Key[Add key: 1448BF693CA600C799EB935804A562FB79953B49 from Apt::Source proxysql_repo]/Apt_key[Add key: 1448BF693CA600C799EB935804A562FB79953B49 from Apt::Source proxysql_repo]/ensure: created
Notice: /Stage[main]/Proxysql::Repo/Apt::Source[proxysql_repo]/Apt::Setting[list-proxysql_repo]/File[/etc/apt/sources.list.d/proxysql_repo.list]/ensure: defined content as '{md5}301a45a0513dfaa4a245df009c1b565a'
Info: /Stage[main]/Proxysql::Repo/Apt::Source[proxysql_repo]/Apt::Setting[list-proxysql_repo]/File[/etc/apt/sources.list.d/proxysql_repo.list]: Scheduling refresh of Class[Apt::Update]
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install proxysql' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package proxysql
Error: /Stage[main]/Proxysql::Install/Package[proxysql]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install proxysql' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package proxysql
Notice: /Stage[main]/Proxysql::Install/File[proxysql-datadir]/ensure: created
Info: Class[Proxysql::Install]: Unscheduling all events on Class[Proxysql::Install]`

## Any additional information you'd like to impart

Maybe its a problem with the puppet-apt module used. For me i'am using 4.5.0

**Comment by bastelfreak** [comment]
Hi @CyberLine we have acceptance tests enables for debian 9:
https://github.com/voxpupuli/puppet-proxysql/blob/74940ee0e82a05ee0fab026dc2c91d3f94842e99/.travis.yml#L88-L99

The test is pretty simply but we sheck for idempotency:
https://github.com/voxpupuli/puppet-proxysql/blob/74940ee0e82a05ee0fab026dc2c91d3f94842e99/spec/acceptance/class_spec.rb#L7-L13

Can you update your apt module to the latest version and check if it still fails for you?

**Comment by mcrauwel** [comment]
@bastelfreak this is testing for puppet5 on debian9, he's using puppet4

**Comment by mcrauwel** [comment]
@CyberLine the tests show that the module is running `apt-get update` after provisioning the repository and before the installation of the package (as it should be)

```  Notice: /Stage[main]/Proxysql::Repo/Apt::Source[proxysql_repo]/Apt::Key[Add key: 1448BF693CA600C799EB935804A562FB79953B49 from Apt::Source proxysql_repo]/Apt_key[Add key: 1448BF693CA600C799EB935804A562FB79953B49 from Apt::Source proxysql_repo]/ensure: created
  Notice: /Stage[main]/Proxysql::Repo/Apt::Source[proxysql_repo]/Apt::Setting[list-proxysql_repo]/File[/etc/apt/sources.list.d/proxysql_repo.list]/ensure: defined content as '{md5}301a45a0513dfaa4a245df009c1b565a'
  Info: /Stage[main]/Proxysql::Repo/Apt::Source[proxysql_repo]/Apt::Setting[list-proxysql_repo]/File[/etc/apt/sources.list.d/proxysql_repo.list]: Scheduling refresh of Class[Apt::Update]
  Info: Class[Apt::Update]: Scheduling refresh of Exec[apt_update]
  Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 event
  Notice: /Stage[main]/Proxysql::Install/Package[proxysql]/ensure: created
```

I've had issues with the behaviour you describe when using older systems that haven't run `apt-get update` for a longer time and have an outdated cache. 

Can you check if you apt-cache is up-to-date?

**Comment by CyberLine** [comment]
I have this behaviour with other Modules too. So i think its apt 4.5.0 related.
